language:
    - php

php:
    - 5.4
    - 5.5
    
before_script:
    - export PLUGIN_DIR=$(pwd)
    - export PLUGIN_SLUG=$(basename $(pwd) | sed 's/^wp-//')
    - pear config-set auto_discover 1
    - pear install PHP_CodeSniffer
    - cd $(pear config-get php_dir)/PHP/CodeSniffer/Standards/
    - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
    - cd WordPress-Coding-Standards/
    - git checkout -b master origin/master
    - cd $(pear config-get php_dir)/PHP/CodeSniffer/Standards/
    - ln -s WordPress-Coding-Standards/WordPress WordPress
    - ln -s WordPress-Coding-Standards/WordPress-Core WordPress-Core
    - ln -s WordPress-Coding-Standards/WordPress-Extra WordPress-Extra
    - ln -s WordPress-Coding-Standards/WordPress-VIP WordPress-VIP
    - cd $PLUGIN_DIR
    - phpenv rehash
    - npm install -g jshint
    - if [ -e phpunit.xml ] || [ -e phpunit.xml.dist ]; then bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION; fi
